"""Render standalone CloudFormation templates from reviewed Python Lambda modules."""
from __future__ import annotations

import argparse
import ast
from pathlib import Path


ROOT = Path(__file__).resolve().parent
TEMPLATE_LIMIT = 51_200
TEMPLATE_NAMES = ("bedrock-logging", "bedrock-central-bucket")
HANDLER_NAMES = ("logging_configuration", "vantage_role_lookup")
INDENT = " " * 10
HEADER = "# Generated by render_templates.py; edit templates/ and bedrock_demo/lambda_handlers/.\n"


def is_bundled_import(node: ast.stmt) -> bool:
    """Return whether an import statement is satisfied by the inline bundle itself."""
    if not isinstance(node, ast.ImportFrom):
        return False
    module = node.module or ""
    return module == "__future__" or module.startswith("bedrock_demo.")


def without_local_imports(source: str) -> str:
    """Return source with imports supplied by the inline bundle removed."""
    tree = ast.parse(source)
    removed = {line for node in tree.body if is_bundled_import(node)
               for line in range(node.lineno, node.end_lineno + 1)}
    return "".join(line for number, line in enumerate(source.splitlines(keepends=True), 1)
                   if number not in removed)


def inline_module(core_source: str, handler_source: str) -> str:
    """Return one importable index module containing the shared core and AWS handler."""
    source = "from __future__ import annotations\n\n" + without_local_imports(core_source)
    source += "\n\n" + without_local_imports(handler_source)
    compile(source, "index.py", "exec")
    return source


def indented(source: str) -> str:
    """Return module source indented for a YAML literal block, blank lines left empty."""
    return "\n".join(INDENT + line if line else "" for line in source.rstrip().splitlines())


def rendered_template(template: str, modules: dict[str, str]) -> str:
    """Return a deterministic template with indented inline module placeholders expanded."""
    result = template
    for name, source in modules.items():
        result = result.replace(f"{INDENT}@@{name}@@", indented(source))
    if "@@" in result:
        raise ValueError("Unresolved template placeholder.")
    result = HEADER + result
    if len(result.encode()) > TEMPLATE_LIMIT:
        raise ValueError(f"Template exceeds the {TEMPLATE_LIMIT}-byte CloudFormation "
                         "TemplateBody limit.")
    return result


def render_all(root: Path, check: bool) -> None:
    """Write both deployable templates or fail when generated files have drifted."""
    core = (root / "bedrock_demo/core/lifecycle.py").read_text()
    handlers = {name.upper(): inline_module(
        core, (root / f"bedrock_demo/lambda_handlers/{name}.py").read_text())
        for name in HANDLER_NAMES}
    for name in TEMPLATE_NAMES:
        result = rendered_template((root / f"templates/{name}.yaml.in").read_text(), handlers)
        output = root / f"{name}.yaml"
        if check:
            if not output.exists() or output.read_text() != result:
                raise ValueError(f"{output.name} is stale; run python3 render_templates.py.")
        else:
            output.write_text(result)


def main() -> None:
    """Render templates or check committed generated files without AWS access."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    render_all(ROOT, args.check)


if __name__ == "__main__":
    main()
